# Generated by cucumber-sinatra. (2014-12-31 10:47:20 -0800)
require 'simplecov'
#SimpleCov.start

ENV['RACK_ENV'] = 'test'
puts "PATH TO TEST: "+File.join(File.dirname(__FILE__), '..', '..', 'app')
require File.join(File.dirname(__FILE__), '..', '..', 'app')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'rack_session_access'
require 'byebug'
puts "ANtes de cargar capybara"
Capybara.app = HangpersonApp
puts "INICIALIZADA CAPyBARA APP"
Capybara.app.configure do |app|
  app.use RackSessionAccess::Middleware
end
puts "Definiendo HangerWorld"
class HangpersonAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

puts "Inicializando el Worl"
World do
  HangpersonAppWorld.new
end
puts "saliendo de ENV"
